# Generated by Django 3.2.4 on 2022-09-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerInfo',
            fields=[
                ('version', models.BigIntegerField(default=1)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_user', models.BigIntegerField()),
                ('ud_date', models.DateTimeField(auto_now=True, null=True)),
                ('ud_user', models.BigIntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('overview', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'career_info',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('version', models.BigIntegerField(default=1)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_user', models.BigIntegerField()),
                ('ud_date', models.DateTimeField(auto_now=True, null=True)),
                ('ud_user', models.BigIntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('version', models.BigIntegerField(default=1)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_user', models.BigIntegerField()),
                ('ud_date', models.DateTimeField(auto_now=True, null=True)),
                ('ud_user', models.BigIntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('version', models.BigIntegerField(default=1)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_user', models.BigIntegerField()),
                ('ud_date', models.DateTimeField(auto_now=True, null=True)),
                ('ud_user', models.BigIntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('overview', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('version', models.BigIntegerField(default=1)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_user', models.BigIntegerField()),
                ('ud_date', models.DateTimeField(auto_now=True, null=True)),
                ('ud_user', models.BigIntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mail_address', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('authority', models.BigIntegerField(blank=True, default=0, null=True)),
                ('state', models.BigIntegerField(blank=True, default=1, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('version', models.BigIntegerField(default=1)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_user', models.BigIntegerField()),
                ('ud_date', models.DateTimeField(auto_now=True, null=True)),
                ('ud_user', models.BigIntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name_kana', models.CharField(max_length=20)),
                ('last_name_kana', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('birthday', models.DateTimeField()),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='ProjectRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.BigIntegerField(default=1)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_user', models.BigIntegerField()),
                ('ud_date', models.DateTimeField(auto_now=True, null=True)),
                ('ud_user', models.BigIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'project_relation',
            },
        ),
        migrations.CreateModel(
            name='ProjectInfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.BigIntegerField(default=1)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_user', models.BigIntegerField()),
                ('ud_date', models.DateTimeField(auto_now=True, null=True)),
                ('ud_user', models.BigIntegerField()),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('project_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
            options={
                'db_table': 'project_info_item',
            },
        ),
        migrations.CreateModel(
            name='MasterItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.BigIntegerField(default=1)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_user', models.BigIntegerField()),
                ('ud_date', models.DateTimeField(auto_now=True, null=True)),
                ('ud_user', models.BigIntegerField()),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
            options={
                'db_table': 'master_item',
            },
        ),
        migrations.CreateModel(
            name='DepartmentRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.BigIntegerField(default=1)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_user', models.BigIntegerField()),
                ('ud_date', models.DateTimeField(auto_now=True, null=True)),
                ('ud_user', models.BigIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'department_relation',
            },
        ),
        migrations.CreateModel(
            name='CareerInfoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.BigIntegerField(default=1)),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('add_user', models.BigIntegerField()),
                ('ud_date', models.DateTimeField(auto_now=True, null=True)),
                ('ud_user', models.BigIntegerField()),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('career_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.careerinfo')),
            ],
            options={
                'db_table': 'career_info_item',
            },
        ),
        migrations.AddField(
            model_name='careerinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddConstraint(
            model_name='masteritem',
            constraint=models.UniqueConstraint(fields=('company', 'key', 'value'), name='master_unique'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='department_unique'),
        ),
    ]
