# Generated by Django 3.2.4 on 2022-09-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
