# Generated by Django 3.2.4 on 2022-09-07 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_lastlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastLogin',
            new_name='last_login',
        ),
    ]
